print("Hello World!")
print("Hello Again!")
print("I like typing this.")
print("This is fun.")
print("Yay! Printing.")
print("I'd much rather you 'not'.")
print('I "said" do not touch this.')
print("Make your script print another line.")
# print("Put a # (octothorpe) character at the beginning of a line. What did it do? Try to find out what this character does.")
